# Generated by Django 2.2 on 2019-04-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='block_type',
            new_name='blog_type',
        ),
    ]
