# Generated by Django 2.2 on 2019-05-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190509_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
